# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab762a71300b177bb9162f2a9e306af7aa890b65071becca54613965848c084a7643f8d2de8ec7b3ee683316b4e75e396d1affdccb08637a1d9497c50dafed70

test:
  secret_key_base: f8b66a50f2be42da2e7fc76a7a4d1373113cc958d56ee463b5557ea7772063850892d5c9ec1003e881d1a72673040e49487c4c9671bf9d59ee95156be7393dfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
